/**
 * @file DbWerkzeugAdapter.cpp
 * @brief UPDATE a werkzeug-hashed password in a container's SQLite DB. The hash
 *        is generated by the container's own werkzeug so the format matches.
 */
#include "rotator/Adapters.h"
#include "rotator/AdapterUtil.h"
#include "rotator/DockerExec.h"

#include <stdexcept>

namespace vault::rotator
{

void DbWerkzeugAdapter::rotate(const Json::Value& p,
                               const std::string& newPassword)
{
    std::string code =
        "import sqlite3; from werkzeug.security import generate_password_hash; "
        "h = generate_password_hash(" + pyRepr(newPassword) +
        "); conn = sqlite3.connect(" + pyRepr(requireParam(p, "db_path")) +
        "); conn.execute('UPDATE " + requireParam(p, "table") + " SET " +
        requireParam(p, "hash_column") + "=? WHERE " +
        requireParam(p, "username_column") + "=?', (h, " +
        pyRepr(requireParam(p, "username")) +
        ")); conn.commit(); conn.close(); print('ok')";
    if (dockerPython(requireParam(p, "db_container"), code).find("ok") ==
        std::string::npos)
        throw std::runtime_error("unexpected output from sqlite update");
}

Json::Value DbWerkzeugAdapter::status(const Json::Value& p)
{
    std::string code =
        "import sqlite3; conn = sqlite3.connect(" +
        pyRepr(requireParam(p, "db_path")) + "); row = conn.execute('SELECT " +
        requireParam(p, "hash_column") + " FROM " + requireParam(p, "table") +
        " WHERE " + requireParam(p, "username_column") + "=?', (" +
        pyRepr(requireParam(p, "username")) +
        ",)).fetchone(); conn.close(); print(len(row[0]) if row else 'NONE')";

    Json::Value out;
    std::string user = requireParam(p, "username");
    try {
        std::string o = dockerPython(requireParam(p, "db_container"), code);
        if (o == "NONE") {
            out["present"] = false;
            out["username"] = user;
        } else {
            out["present"] = true;
            out["username"] = user;
            out["hash_len"] = std::stoi(o);
        }
    } catch (const std::exception& e) {
        out["present"] = false;
        out["error"] = e.what();
    }
    return out;
}

} // namespace vault::rotator
