// genblowfish.cpp — derive the Blowfish P-array + S-box initial constants.
//
// Those 1042 words are simply the fractional hexadecimal digits of pi
// (P[0] = 0x243F6A88 = first 8 hex digits after "3."). We compute pi to enough
// hex places with EXACT big-integer arithmetic via Machin's formula
//   pi = 16*atan(1/5) - 4*atan(1/239)
// then slice the hex digits. No floating point, fully reproducible. Output is
// an #include-able C array. Run once; the result is checked into BlowfishInit.inc.
//
// Build: g++ -std=c++20 -O2 tools/genblowfish.cpp -o /tmp/genbf && /tmp/genbf
#include <cstdint>
#include <cstdio>
#include <string>
#include <vector>

using Big = std::vector<uint32_t>; // little-endian base-2^32 limbs

static void trim(Big& a) { while (a.size() > 1 && a.back() == 0) a.pop_back(); }

static void mulSmall(Big& a, uint32_t m)
{
    uint64_t carry = 0;
    for (auto& limb : a) {
        uint64_t cur = (uint64_t)limb * m + carry;
        limb = (uint32_t)cur;
        carry = cur >> 32;
    }
    while (carry) { a.push_back((uint32_t)carry); carry >>= 32; }
}

static uint32_t divSmall(Big& a, uint32_t d) // returns remainder
{
    uint64_t rem = 0;
    for (size_t i = a.size(); i-- > 0;) {
        uint64_t cur = (rem << 32) | a[i];
        a[i] = (uint32_t)(cur / d);
        rem = cur % d;
    }
    trim(a);
    return (uint32_t)rem;
}

static bool isZero(const Big& a) { return a.size() == 1 && a[0] == 0; }

static void subInPlace(Big& a, const Big& b) // a -= b, assumes a >= b
{
    int64_t borrow = 0;
    for (size_t i = 0; i < a.size(); ++i) {
        int64_t bi = i < b.size() ? b[i] : 0;
        int64_t cur = (int64_t)a[i] - bi - borrow;
        if (cur < 0) { cur += (int64_t)1 << 32; borrow = 1; } else borrow = 0;
        a[i] = (uint32_t)cur;
    }
    trim(a);
}

static void addInPlace(Big& a, const Big& b)
{
    uint64_t carry = 0;
    for (size_t i = 0; i < b.size() || carry; ++i) {
        if (i == a.size()) a.push_back(0);
        uint64_t cur = (uint64_t)a[i] + (i < b.size() ? b[i] : 0) + carry;
        a[i] = (uint32_t)cur;
        carry = cur >> 32;
    }
}

// arctan(1/x) * 2^(4*N), exact (series truncates when the running power hits 0).
static Big atanScaled(uint32_t x, uint32_t N)
{
    Big scale(1, 0);                       // 2^(4N)
    scale.assign((4u * N) / 32 + 1, 0);
    scale[(4u * N) / 32] = 1u << ((4u * N) % 32);

    Big pow = scale;                       // SCALE / x  (the k=0 power, before /x)
    divSmall(pow, x);
    uint32_t x2 = x * x;
    Big sum(1, 0);
    uint32_t k = 0;
    bool add = true;
    while (!isZero(pow)) {
        Big term = pow;
        divSmall(term, 2 * k + 1);
        if (add) addInPlace(sum, term); else subInPlace(sum, term);
        add = !add;
        divSmall(pow, x2);
        ++k;
    }
    return sum;
}

static std::string toHex(const Big& a)
{
    std::string s;
    char buf[9];
    snprintf(buf, sizeof buf, "%x", a.back());
    s += buf;
    for (size_t i = a.size() - 1; i-- > 0;) {
        snprintf(buf, sizeof buf, "%08x", a[i]);
        s += buf;
    }
    return s;
}

int main()
{
    const uint32_t WORDS = 1042;
    const uint32_t HEXDIGITS = WORDS * 8;          // 8336
    const uint32_t N = HEXDIGITS + 32;             // guard digits

    Big a = atanScaled(5, N);   mulSmall(a, 16);
    Big b = atanScaled(239, N); mulSmall(b, 4);
    subInPlace(a, b);                              // a = pi * 2^(4N)

    std::string hex = toHex(a);                    // "3243f6a88..."
    if (hex[0] != '3') { fprintf(stderr, "BUG: pi hex != 3...\n"); return 1; }
    std::string frac = hex.substr(1);              // drop integer nibble

    std::vector<uint32_t> words(WORDS);
    for (uint32_t i = 0; i < WORDS; ++i)
        words[i] = (uint32_t)strtoul(frac.substr(i * 8, 8).c_str(), nullptr, 16);

    if (words[0] != 0x243F6A88u || words[1] != 0x85A308D3u ||
        words[2] != 0x13198A2Eu || words[3] != 0x03707344u) {
        fprintf(stderr, "BUG: leading Blowfish words mismatch\n");
        return 1;
    }

    printf("// Generated by tools/genblowfish.cpp — fractional hex digits of pi.\n");
    printf("// P-array = first 18 words, S-boxes = next 1024. Do not edit.\n");
    printf("static const uint32_t BF_INIT[1042] = {\n");
    for (uint32_t i = 0; i < WORDS; ++i) {
        if (i % 6 == 0) printf("   ");
        printf(" 0x%08x,", words[i]);
        if (i % 6 == 5) printf("\n");
    }
    printf("\n};\n");
    fprintf(stderr, "OK: 1042 words, P[0]=0x%08x P[1]=0x%08x\n", words[0], words[1]);
    return 0;
}
