"""inventory-host: capture what's installed on the current host so the
information needed to rebuild this server on a fresh Debian box stays in
git. Writes:

    docs/host-baseline.md    — human-readable summary (third-party repos,
                                non-apt installs, runtime stack)
    docs/host-apt-manual.txt — full `apt-mark showmanual` list (raw)

Re-run whenever you install something new on the host. Read-only: never
modifies installed packages or apt sources.
"""
from __future__ import annotations

import argparse
import datetime as dt
import re
import subprocess
from pathlib import Path

from . import REPO_ROOT

DOCS = REPO_ROOT / "docs"
BASELINE_MD = DOCS / "host-baseline.md"
APT_LIST = DOCS / "host-apt-manual.txt"


def _run(cmd: list[str]) -> str:
    proc = subprocess.run(cmd, capture_output=True, text=True)
    return proc.stdout.strip()


def _apt_manual() -> list[str]:
    return sorted(_run(["apt-mark", "showmanual"]).splitlines())


def _os() -> dict:
    return {
        "distro": _run(["lsb_release", "-i", "-s"]) or "unknown",
        "version": _run(["lsb_release", "-r", "-s"]) or "unknown",
        "codename": _run(["lsb_release", "-c", "-s"]) or "unknown",
        "arch": _run(["dpkg", "--print-architecture"]) or "unknown",
        "kernel": _kernel(),
    }


def _kernel() -> str:
    out = _run(["dpkg-query", "-W", "-f", "${Version}", "linux-image-amd64"])
    return out or "unknown"


def _third_party_sources() -> list[dict]:
    """Anything in /etc/apt/sources.list.d/ that is NOT debian.org."""
    out: list[dict] = []
    src_dir = Path("/etc/apt/sources.list.d")
    if not src_dir.exists():
        return out
    for p in sorted(src_dir.iterdir()):
        text = p.read_text(errors="replace") if p.is_file() else ""
        if not text.strip():
            continue
        if "debian.org" in text or "debian.mirror" in text:
            continue
        uri = ""
        m = re.search(r"^URIs?:\s*(\S+)", text, re.MULTILINE)
        if m:
            uri = m.group(1)
        else:
            m = re.search(r"^deb\s+(?:\[[^\]]+\]\s+)?(\S+)", text, re.MULTILINE)
            if m:
                uri = m.group(1)
        key = ""
        m = re.search(r"Signed-By:\s*(\S+)", text)
        if m:
            key = m.group(1)
        else:
            m = re.search(r"signed-by=(\S+?)\]", text)
            if m:
                key = m.group(1)
        out.append({"file": p.name, "uri": uri, "key": key})
    return out


def _node_version() -> str | None:
    """If nvm is installed, return the active node version."""
    nvm_dir = Path.home() / ".nvm" / "versions" / "node"
    if not nvm_dir.exists():
        return None
    versions = sorted(p.name for p in nvm_dir.iterdir() if p.is_dir())
    return versions[-1] if versions else None


def _pip_packages(of_interest: list[str]) -> dict[str, str]:
    """Return installed versions of pip packages we care about for IaC."""
    out = _run(["python3", "-m", "pip", "list", "--format=freeze"])
    versions = dict(line.split("==", 1) for line in out.splitlines() if "==" in line)
    return {p: versions[p] for p in of_interest if p in versions}


def _nomachine() -> str | None:
    v = _run(["dpkg-query", "-W", "-f", "${Version}", "nomachine"])
    return v or None


def _write_apt_list(manual: list[str]) -> None:
    APT_LIST.write_text("\n".join(manual) + "\n")


def _render_baseline(captured_at: str, os_info: dict, sources: list[dict],
                     manual_count: int, node: str | None, pip: dict[str, str],
                     nomachine: str | None) -> str:
    src_rows = "\n".join(
        f"| `{s['file']}` | `{s['uri']}` | `{s['key'] or '—'}` |"
        for s in sources
    ) or "| _none detected_ | | |"

    pip_lines = (
        "\n".join(f"- `{name}=={ver}`" for name, ver in pip.items())
        or "_(none of the tracked packages were found)_"
    )

    return f"""# Host baseline

Snapshot of the host this stack runs on. Generated by `setup.py inventory-host`
on {captured_at}. If the box gets nuked, this file plus
`docs/host-apt-manual.txt` tells you what to reinstall on a fresh
{os_info['distro']} {os_info['version']} ({os_info['codename']}) host before
`setup.py up` can succeed.

## OS

- **Distribution**: {os_info['distro']} {os_info['version']} ({os_info['codename']})
- **Architecture**: {os_info['arch']}
- **Kernel** (`linux-image-amd64`): {os_info['kernel']}

## Third-party apt sources

| File | URI | Key |
| --- | --- | --- |
{src_rows}

Stock Debian sources are not listed — they're whatever the installer puts in
place plus a Constant.com mirror.

## Manually-installed apt packages

`apt-mark showmanual` returned **{manual_count}** entries. Full list lives in
`docs/host-apt-manual.txt` so this file stays readable. Highlights for the
runtime + build chain:

- Container runtime: `docker-ce`, `docker-buildx-plugin`, `docker-compose-plugin`,
  `containerd.io`
- Python: `python3` (3.13.x), `python3-pip`, `python3-poetry`
- Toolchain: `cmake`, `build-essential`, `gcc-mingw-w64-x86-64`, the
  `-dev` libraries the C++ daemons (`dbal`, `media-daemon`, `gameengine`)
  pull in via conan
- VCS + release: `git`, `gh`
- Host hygiene: `ufw`, `chrony`, `unattended-upgrades`, `cloud-init`,
  `qemu-guest-agent`
- Desktop (optional on a headless rebuild): `xfce4-*`, `terminator`,
  `google-chrome-stable`, `gparted`

## Non-apt installs

### Node.js — nvm

{('Latest installed version: `' + node + '`') if node else '_nvm not detected_'}

Installed under `~/.nvm/`. `corepack` and `npm` are the only globals.

### Python pip packages

{pip_lines}

`bcrypt` is required by the rotator's `db_bcrypt` adapter.

### NoMachine

{('Version `' + nomachine + '`, installed from a `.deb` (see `~/Documents/GitHub/nomachine_*.deb`).') if nomachine else '_NoMachine not detected._'}

## Reproduce on a fresh Debian host

See `setup.py install-host-deps` (TODO) for an automated path. Manual
checklist:

1. Add the third-party apt repos above (key + sources file in
   `/etc/apt/keyrings/` and `/etc/apt/sources.list.d/`).
2. `apt-get install` the runtime + toolchain packages.
3. `usermod -aG docker $USER`, log out + back in.
4. Install nvm and `nvm install <node-version>`.
5. `pip install bcrypt`.
6. Clone this repo, then `python3 scripts/setup.py clone-repos`.
7. `python3 scripts/setup.py secrets --rotate-ssh-key --nexus-password <pw>`.
8. `python3 scripts/setup.py up`.
9. `python3 scripts/setup.py register-jobs`.

NoMachine + the XFCE desktop are optional unless you want to run dev tools
on the same host.
"""


def cmd_inventory_host(args: argparse.Namespace) -> int:
    DOCS.mkdir(parents=True, exist_ok=True)
    manual = _apt_manual()
    captured_at = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d")
    content = _render_baseline(
        captured_at=captured_at,
        os_info=_os(),
        sources=_third_party_sources(),
        manual_count=len(manual),
        node=_node_version(),
        pip=_pip_packages(["bcrypt", "cryptography", "jinja2", "requests"]),
        nomachine=_nomachine(),
    )
    if args.print:
        print(content)
        return 0
    BASELINE_MD.write_text(content)
    _write_apt_list(manual)
    print(f"wrote {BASELINE_MD.relative_to(REPO_ROOT)} ({len(manual)} apt packages)")
    print(f"wrote {APT_LIST.relative_to(REPO_ROOT)}")
    return 0
